using UnityEngine;
using System.Collections;

public enum MTAPoint
{
	MINI_BUY_FIRE,
	MINI_BUY_DIANJU,
	MINI_BUY_DOUBLE_SHOUQIANG,
	MINI_BUY_DOUBLE_FIRE,
	MINI_BUY_DOUBLE_JIQIANG,
	MINI_BUY_DOUBLE_LIUDAN,
	MINI_BUY_DOUBLE_M4,
	MINI_BUY_DOUBLE_SANDAN,
	MINI_BUY_PET_1,
	MINI_BUY_PET_2,
	MINI_BUY_PET_3,
	MINI_BUY_PET_4,
	MINI_BUY_PET_5,
	MINI_BUY_PET_6,
	MINI_BUY_PET_7,
	MINI_BUY_PET_SOLT,
	MINI_BUY_XUE,
	MINI_BUY_BINDONG,
	MINI_BUY_JIATELIN,
	MINI_BUY_AOE,
	MINI_BUY_TILI_1,
	MINI_BUY_TILI_5,
	MINI_BUY_TILI_12,
	MINI_BUY_TILI_20,
	MINI_BUY_TILI_50,
	MINI_BUY_TILI_120,
	MINI_BUY_GOLD_500,
	MINI_BUY_GOLD_2500,
	MINI_BUY_GOLD_5200,
	MINI_BUY_GOLD_11000,
	MINI_BUY_GOLD_28000,
	MINI_BUY_GOLD_88000,
	MINI_BUY_DIAMOND_TYPE_1,
	MINI_BUY_DIAMOND_TYPE_2,
	MINI_BUY_DIAMOND_TYPE_3,
	MINI_BUY_DIAMOND_TYPE_4,
	MINI_BUY_DIAMOND_TYPE_5,
	MINI_BUY_DIAMOND_TYPE_6,
	MINI_BUY_SALE_TYPE_1,
	MINI_BUY_SALE_TYPE_2,
	MINI_BUY_SALE_TYPE_3,
	MINI_BUY_SALE_TYPE_4,
	MINI_BUY_SALE_TYPE_5,
	MINI_BUY_SALE_TYPE_6,
	MINI_BUY_VIP_TYPE_1,
	MINI_BUY_VIP_TYPE_2,
	MINI_BUY_GOLD_DOUBLE,
	MINI_BUY_DIAMOND_PERCENT_20,
	MINI_BUY_BULLET_CAPCITY,
	MINI_BUY_FUHUO_1,
	MINI_BUY_FUHUO_2,
	MINI_BUY_FUHUO_3,
	MINI_BUY_DIR_PASS,
	MINI_UPGRADE_DAO,
	MINI_UPGRADE_DIANJU,
	MINI_UPGRADE_SHOUQIANG,
	MINI_UPGRADE_SANDAN,
	MINI_UPGRADE_LIUDAN,
	MINI_UPGRADE_M4,
	MINI_UPGRADE_JIQIANG,
	MINI_UPGRADE_FIRE,
	MINI_UPGRADE_DOUBLE_SHOUQIANG,
	MINI_UPGRADE_DOUBLE_SANDAN,
	MINI_UPGRADE_DOUBLE_LIUDAN,
	MINI_UPGRADE_DOUBLE_M4,
	MINI_UPGRADE_DOUBLE_JIQIANG,
	MINI_UPGRADE_DOUBLE_FIRE,
	MINI_UPGRADE_FU_SPEED,
	MINI_UPGRADE_FU_KUANGBAO,
	MINI_UPGRADE_FU_HUIFU,
	MINI_UPGRADE_FU_ZHAOHUAN,
	MINI_UPGRADE_PET_1,
	MINI_UPGRADE_PET_2,
	MINI_UPGRADE_PET_3,
	MINI_UPGRADE_PET_4,
	MINI_UPGRADE_PET_5,
	MINI_UPGRADE_PET_6,
	MINI_UPGRADE_PET_7,
	MINI_UPGRADE_HERO_1,
	MINI_BUY_MAP2,
	MINI_USE_PET_1,
	MINI_USE_PET_2,
	MINI_USE_PET_3,
	MINI_USE_PET_4,
	MINI_USE_PET_5,
	MINI_USE_PET_6,
	MINI_USE_PET_7,
	MINI_USE_BINDONG,
	MINI_USE_XUE,
	MINI_USE_AOE,
	MINI_USE_JIATELIN,
}

public class MTAManager {

	private static bool IsInitialized = false;
	private static MTAPlatform platform = null;

	public static void Init()
	{
		if (!IsInitialized)
		{
			platform = new TencentMTA();
			platform.Init();

			IsInitialized = true;
		}
	}

	public static void DoEvent(MTAPoint point)
	{
		if (platform != null)
		{
			platform.DoEvent(point.ToString());
		}
	}
}
